sudo: required
services:
    - docker

before_install:
    - docker build -t alassani/docker-react .

script:
    - docker run -e CI=true alassani/docker-react
    - echo 'Alassani ABODJI has finished the build !'

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-063824834627"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
