version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: web
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - WATCHPACK_POLLING=true # For auto-updating on Windows platform
